// <auto-generated>
// ControllerTemplates.cs
// Generated on 2019/11/13 10:51:45
// Do not edit this file.
// This file can be generated from the ControllerDataFiles inspector.
// </auto-generated>

// Copyright (c) 2019 Augie R. Maddox, Guavaman Enterprises. All rights reserved.

#if REWIRED_USE_USER_DEFINED_CONTROLLER_TEMPLATES

#pragma warning disable 0219
#pragma warning disable 0618
#pragma warning disable 0649
#pragma warning disable 0067

namespace Rewired {
    
    #region Interfaces
    
    #endregion
    
    #region Classes
    
    #endregion
}

#region Internal

namespace Rewired.Internal {
    using System;
    
    /// <summary>
    /// Factory class for creating Controller Templates.
    /// This is for internal use only.
    /// </summary>
    public static partial class ControllerTemplateFactory {
        
        private static readonly Type[] _userTemplateTypes = new Type[0]
        
        private static readonly Type[] _userTemplateInterfaceTypes = new Type[0];
        
        private static IControllerTemplate CreateUser(Guid typeGuid, object payload) {
            return null;
        }
    }
}

#endregion

#endif
